### PR TITLE
Fix/render updates

### PR DESCRIPTION
**Pull request by tibotiber**
Hi! I was trying to perform updates using D3's `enter()`, `update()` and `exit()` methods but was stuck because the mixin currently create the faux node each time `connectFauxDOM` is called. I've made a minor change to simply return the stored node if it exists, instead of overwriting it. I also added an example to showcase the new functionality. Hope this can be useful.

### CODE REVIEW

**Comment by tibotiber** [comment]
@Olical: about breaking changes, some users might implicitly rely on the fact that the faux node is recreated from scratch at each `connectFauxDOM` call. I had not considered it previously. I could leave this API untouched and add another one that implement the new behaviour, something like `reconnectFauxDOM`. Then the first call to `reconnectFauxDOM` would be equivalent to `connectFauxDOM` but subsequent calls would be update-friendly. What do you think? I think it is a safe option and would mean a feature bump (v3.1.0?).

**Comment by tibotiber** [comment]
PR rebased on master

**Comment by tibotiber** [comment]
@Olical any feedback on `reconnectFauxDOM`?

**Comment by Olical** [comment]
I think it'll be okay as it is, it was wrong before. I doubt anyone was relying on the recreation directly. If they are, that's essentially a bug anyway, they can stick on the old version if required.

**Comment by tibotiber** [comment]
@Olical makes sense, and I prefer a simpler API! If you have no additional review I think we're good to merge :)

**Comment by Olical** [comment]
Yep, it's cool. I'll merge and deploy it tonight, sorry about the slowness, it was a holiday weekend here in the UK :smile:

**Pull request merged**
