### PR TITLE
Update package.json

### LINKED ISSUE #12: npm ERR! peerinvalid Peer react-faux-dom@1.1.0 wants react@0.x
[package.json#L44](https://github.com/Olical/react-faux-dom/blob/master/package.json#L44)

```
  "peerDependencies": {
    "react": "0.x"
  }
```

This doesn't match with `0.14.0-rc1` since npm doesn't versions containing [a-Z] characters as releases. (as long as I can remember)

```
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-pure-render-mixin@0.14.0-rc1 wants react@^0.14.0-rc1
npm ERR! peerinvalid Peer react-mirror@0.4.1 wants react@>=0.13.3 || ^0.14.0-beta3 || ^0.14.0-rc1
npm ERR! peerinvalid Peer redbox-react@1.0.5 wants react@>=0.13.2 || ^0.14.0-rc1
npm ERR! peerinvalid Peer react-faux-dom@1.1.0 wants react@0.x
```

### PR DESCRIPTION
**Pull request by Theadd**
`"react": "0.x || ^0.14.0-rc1"`

Fixes #12

### CODE REVIEW

**Comment by Olical** [comment]
Cool, thanks for catching this. Happy to merge but this will probably keep cropping up. Maybe it should just be `*`. I only used `0.x` because a major bump **may** correspond to breaking API changes. It's probably okay to use any version and lock it in future if issues arose. If you want to change that here to also fix the issue I'd be happy to merge that too.

**Comment by Theadd** [comment]
Removing react from peerDependencies and adding it as devDependencies is also a common fix that people have been using in order to avoid those problems to whom is trying to install your module.

Your project name starts with `react` and you also reference react in your README.md. I'm almost certain that no one will try to use this module in a project without react.

**Comment by Olical** [comment]
I wouldn't be adverse to this either, I only used it because it seemed
semantically correct.

**Comment by Theadd** [comment]
Nvm, 0.14.0 released

**Pull request closed without merging**
