### PR TITLE
fix function pass in addEventListener

### PR DESCRIPTION
**Pull request by chilijung**
fix function pass in addEventListener, so it is possible to pass extra parameters while event trigger in d3 events.

I don't know whether it is the best solution. But this help me to achieve passing events and parameters in d3 DOM.

For example:

https://github.com/react-d3/react-d3-tooltip/blob/feature/react-faux-dom/src/utils/voronoi.jsx#L73-L92

```js
 voronoiPath.each(function(p) {
      var evtObj = {
        data: p,
        xScaleSet: xScaleSet,
        yScaleSet: yScaleSet,
        focus: focus,
        stack: stack
      }

      this.addEventListener('mouseover', (e, d) => {
        return focus?
          onMouseOver(e, d.data, d.xScaleSet, d.yScaleSet, d.focus, d.stack):
          onMouseOver(e, d.data, d.xScaleSet, d.yScaleSet)
        }, evtObj)
      this.addEventListener('mouseout', (e, d) => {
        return focus?
          onMouseOut(e, d.data, d.xScaleSet, d.yScaleSet, d.focus, d.stack):
          onMouseOut(e, d.data, d.xScaleSet, d.yScaleSet)
        }, evtObj)
    })
```

By the way, I'm moving my whole react-d3 (http://reactd3.org) library using `react-faux-dom` ! Thank you so much for building this library!

P.S. 
I've see you mention about `d3.mouse` or `d3.event` 

https://github.com/Olical/react-faux-dom/issues/9

In this solution many event properties can be access in `SyntheticEvent` object, like clientX, clientY...

### CODE REVIEW

**Comment by Olical** [comment]
Hey, @chilijung. Thanks for the PR and it's great to hear that you're making use of it, I'll do my best to continually improve this project. As far as this change goes, it actually goes against how `addEventListener` is supposed to work ([MDN docs](https://developer.mozilla.org/es/docs/Web/API/EventTarget/addEventListener)) so I don't think it'd be a good idea to change this.

The best way to achieve this would be something like [_.partialRight](https://lodash.com/docs#partialRight) which is easy enough to implement without lodash too. This allows you to pass arguments through like this in any scenario without modifying the underlying listener.

As for the `d3.event` and `d3.mouse` I'm currently working on a probably breaking change that should fix the event interaction. I'm not sure if it will be enough to fix brushing on it's own, but it's a large step in the right direction.

I'm currently working on a branch that allows you to call `addEventListener` multiple times for the same event (this just replaces the previous event right now) so it behaves like the real thing, not React. I'm also going to pass the *real* DOM event through to the listener, not the synthetic event. You will still be able to access the synthetic event, but this is required to get most of D3 event based systems working.

Are you happy for me to close this in favour of wrapping your listener / partially applying it so we can keep to the normal DOM API?

Thanks a lot!

**Comment by chilijung** [comment]
ok sounds great! Looking forward to it!

And thanks!

**Comment by chilijung** [comment]
>  _.partialRight which is easy enough to implement without lodash too. This allows you to pass arguments through like this in any scenario without modifying the underlying listener.

hmm, @Olical sorry for keep bothering you, could you provide some sample you are saying how you implement using `_.partialRight`, maybe I can help, and send a PR later. (because I really wish it could be done) Thanks!

**Comment by chilijung** [comment]
And one more question, transition seems not working properly 

```js
line.datum(dataset.data)
      .style("stroke", dataset.color)
    .transition()
      .duration(duration)
      .ease("linear")
      .attr("class", `${lineClassName} line`)
      .attr("d", this._setAxes())
```
Can this be fixed?

**Pull request closed without merging**
