### PR TITLE
Implement withFauxDOM without inheritance inversion

### LINKED ISSUE #96: Error running through UglifyJs
There is a new error due to the HOC. I get it when running `yarn build` in a create-react-app. Basically UglifyJs fails to process the HOC, apparently expecting it to be already compiled to ES5. Isn't the lib run through babel in a prepublish step? Not sure how to approach this. Any idea @Olical?

```
react-scripts build 
Creating an optimized production build...
Failed to compile.

static/js/main.2f8d0454.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/react-faux-dom/lib/withFauxDOM.js:4,0]

error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by tibotiber**
Follow up to #96 and #101, fixes #96

### CODE REVIEW

**Comment by tibotiber** [comment]
minimal usage:
```javascript
import React from 'react'
import * as d3 from 'd3'
import {withFauxDOM} from 'react-faux-dom'

class MyReactComponent extends React.Component {
  componentDidMount () {
    const faux = this.props.connectFauxDOM('div', 'chart')
    d3.select(faux)
      .append('div')
      .html('Hello World!')
    this.props.animateFauxDOM(800)
  }

  render () {
    return (
      <div>
        <h2>Here is some fancy data:</h2>
        <div className='renderedD3'>
          {this.props.chart}
        </div>
      </div>
    )
  }
}

MyReactComponent.defaultProps = {
  chart: 'loading'
}

export default withFauxDOM(MyReactComponent)
```

**Comment by Olical** [comment]
screenshot_2017-06-02_12-28-17

**Comment by Olical** [comment]
We just need to update the docs slightly and make sure we've seen it work with an actual animation I guess. Great work though, very happy :smile:

**Comment by Olical** [comment]
I'm updating the readme now.

**Comment by Olical** [comment]
If this commit isn't to you're liking, feel free to rewrite it out of history. I wasn't sure if I'd missed anything or if you wanted to explain things slightly differently in the documentation now? I think the examples should be correct now too.

Hopefully we're not far off of merging! :D

**Comment by Olical** [comment]
screenshot_2017-06-02_12-45-38

Animations are working perfectly in the first example. The second one (with the circles) is super slow though. Maybe there's something up with the "should I render?" checks.

**Comment by tibotiber** [comment]
@Olical I have not yet made `drawFauxDOM()` available via props as it feels more like an internal method. What is your opinion on this?

**Comment by Olical** [comment]
If this approach solves it all for @PeterKey too, I'd say we call this v4.0.3 and :shipit:

**Comment by tibotiber** [comment]
I fixed the "update-with-hoc" example and made some changes to the docs. We still need to decide whether or not `drawFauxDOM()` should be in the props API or internal only and update either the code or the docs.

I saw that you removed the "author" section, we could replace it by a "authors" section or "collaborators" or something similar? 😊

**Comment by Olical** [comment]
I think it's okay outside if it wasn't recommended before. If we need to expose it in the future I guess we can? As long as the examples and docs work fine, I'm happy.

And yeah, it made sense when it was just my work, but since other people have contributed a fair amount now (nudge nudge) I thought it was unfair to claim it entirely as my own. There's always the [contributors](https://github.com/Olical/react-faux-dom/graphs/contributors) page :smile:

I could add a maintainers section if you feel it would be valuable though. I don't really mind.

**Comment by tibotiber** [comment]
I updated the documentation, so it's ready to merge. Do you prefer to squash the commits before that or you don't care?

I think a maintainers section could be cool, it gives people a clear point of contact and can be a way to invite other maintainers maybe?

**Comment by Olical** [comment]
I added a little section for it, I hope that's okay? I'm not saying you have to be a super active maintainer, just that you have collaborator rights and know a bunch :smile:

**Comment by tibotiber** [comment]
Looks great! 😎

**Comment by Olical** [comment]
Alright, let's do this. I don't squash or rebase ever, for better or worse. I prefer to keep the commits as they were and then use git CLI commands to filter things if I need to.

**Comment by tibotiber** [comment]
👍🎉

**Pull request merged**
