### PR TITLE
upgrade a bunch of stuff

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by Olical** [comment]
🎆

**Comment by Olical** [comment]
Published in v4.0.4

**Comment by graingert** [comment]
@Olical you mean 4.0.5?

**Comment by Olical** [comment]
I released it as two different versions. The base React -> dev deps change in 4.0.4, the other changes in 4.0.5, just in case it broke things.

It broke CI and I didn't realise :D I think that was because I used yarn though. JavaScript ¯\_(ツ)_/¯

**Comment by Olical** [comment]
Swapped from `yarn.lock` to `package-lock.json` and it started passing again. No idea. Back to Clojure(Script) I go!

**Comment by graingert** [comment]
Oh that's my fault. I didn't spot the yarn.lock

**Comment by Olical** [comment]
Oh no, wasn't you! Don't worry, I added the file but for some reason it
broke Travis for basically no reason. Just Travis though.

**Pull request merged**
