### PR TITLE
remove react from dependencies

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by Olical** [comment]
Great! 🎉

Thank you very much for the changes, they look good. I'll merge and release soon.

Have you had a chance to use this version against an existing project that depends on RFD?

**Comment by graingert** [comment]
@Olical I pretty desperately need #5d058696 released so I've finished the changes and split low priority upgrades to https://github.com/Olical/react-faux-dom/pull/115.

**Comment by graingert** [comment]
@Olical why can't I tag you?

**Comment by Olical** [comment]
Alright, will publish over lunch. (which is basically now)

**Comment by graingert** [comment]
@Olical   I pretty desperately need 5d058696 released so I've finished the changes and split low priority upgrades to https://github.com/Olical/react-faux-dom/pull/115.

@Olical why can't I tag you?

**Comment by graingert** [comment]
@Olical sorry for all the spam, I'm just trying to demo a github bug to @izuzak

**Comment by Olical** [comment]
I have pasta so I'm deploying over some parmesan. v4.0.4 in < 5 mins.

**Comment by Olical** [comment]
Published in v4.0.5. Thanks for the improvements, @graingert! 😄

**Comment by graingert** [comment]
@Olical hot stuff, thanks for the quick turn-a-round.

**Pull request merged**
