### PR TITLE
support independant documents with react-faux-dom/lib/factory

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@Olical I'm having trouble with different parts of my app writing to `Object.getPrototypeOf(el)`, `el.ownerDocument` and `el.ownerDocument.defaultView`

Not only do these interactions cause conflicts with different parts, they also cause a memory leak when they hang around.

**Comment by graingert** [comment]
Not only that, I want to wrap my whole rfd Element tree in `es7-membrane` to do change detection.

**Comment by Olical** [comment]
Oh, interesting, I can see why this would be helpful. I'll have a proper read through ASAP, but I like the concept. A little busy planning a holiday this week but will try to sort it out 😄

I have no idea what an membrane is, but I guess it's watching objects in a way. Again, not something I really considered because I don't particularly like watching mutable things, personally. If it makes that work and doesn't break anything 🎉

**Comment by graingert** [comment]
Right now the global window memory leak is my main concern

**Comment by Olical** [comment]
Okay, beginning to look at this now, quite a drastic code change. Is this actually transparent to the consumer? Just a hunch, but would you not be able to get around this with deep object cloning on your part? Which would save changing this to use factories?

**Comment by graingert** [comment]
>  Is this actually transparent to the consumer?

Yes, the tests pass with no changes

> Just a hunch, but would you not be able to get around this with deep object cloning on your part?

No, cloneDeep won't work here because the Element constructor is hard coded to a global window

**Pull request merged**
