### PR TITLE
Add codesandbox link for examples

### PR DESCRIPTION
**Pull request by tibotiber**
I've posted the 3 examples (minimal, update and animate) to CodeSandbox to make it more beginner friendly and make it easy to play and test without setting up anything. CodeSandbox would also be great for tests and minimal examples in bug reports in the future.

As CodeSandbox is great for create-react-app (CRA) projects, I've copied over the 2 examples from the repo into separate repos with CRA. It generally makes it easier to fork or update separately from the lib. I'd suggest moving these out of the repo completely but that's completely up to you. I'd understand if you prefer to keep things in.

edit: I've invited you on the 2 example repos, at least so you can update the sandbox

### CODE REVIEW

**Comment by Olical** [comment]
This actually looks really good to me, I like it. People can click a link and see something working. This is the first I'm hearing of CodeSandbox, but it looks nice. I hope it continues to run for the foreseeable future.

I'm happy to merge this since it deletes a bunch of code and makes it actually runnable elsewhere. Nice work and thank you very much! :smile:

**Comment by Olical** [comment]
I just checked the links are all okay still, they seem to be. Hopefully we don't have any 404s on our hands. Another great PR :tada:

**Comment by tibotiber** [comment]
Glad you like it 🍻. CodeSandbox is only 2-3 months old but it's getting some really huge traction. I got the idea from Redux, they are currently posting sandbox links for their examples so hopefully we're safe on the longevity 😉.

**Comment by Olical** [comment]
If you're happy, feel free to merge. I think this is great functionality and I always like to see more lines removed than added, for any reason.

**Pull request merged**
