### PR TITLE
Added UMD build to project

### PR DESCRIPTION
**Pull request by kennetpostigo**
I'm currently using this library and was playing around with it on my local machine. When I tried to import it into codepen or jsfiddle the console complained because it's not a UMD build. I added a webpack to create a UMD production and development build for your library. The UMD build lives in the `dist` folder. The folder contains 2 files, `ReactFauxDOM.js`(development) and `ReactFauxDom.min.js`(production). 
I didn't change any code at all just additions. Take it for a spin 😀

### CODE REVIEW

**Comment by kennetpostigo** [comment]
It seems to be failing because the `dist/ReactFauxDOM.js` file is being compiled to a UMD build so the files are still being checked my `Standard`

**Comment by Olical** [comment]
Hey, thanks for the PR!

Whilst I agree with making it easier to import into various module systems, I'm not really okay with committing `dist` files into the repository. Maybe this should be something that's pushed to a CDN instead?

I haven't encountered this problem myself since we include it into packages that use webpack themselves, I can see how it'd be problematic to load into a normal web page.

**Comment by kennetpostigo** [comment]
@Olical theres this new cdn called `npmcdn` from which all of npm is served. If you don't want to commit the dist files, you can always put it in the `.gitignore` 😀

**Comment by Olical** [comment]
[npmcdn](https://npmcdn.com/) looks pretty good and reliable too. They have instructions on exactly what we're doing here. I'd be happy to do that since it won't be in git, we can then document these CDN URLs in the readme as something you can hotlink to or download as a static browser build version if you aren't using webpack etc.

I just built this with the assumption that you're using browserify / webpack since most React projects are (to my knowledge).

**Comment by Olical** [comment]
Will have a UMD in a CDN in v2.6.0 :)

**Comment by Olical** [comment]
Here you go https://npmcdn.com/react-faux-dom@2.6.2/dist/ReactFauxDOM.min.js

**Pull request closed without merging**
