### PR TITLE
Replace Mixins by an HOC

### PR DESCRIPTION
**Pull request by tibotiber**
This is a WIP PR for replacing the mixins by an higher order component.

- [x] remove mixins
- [x] implement HOC `withFauxDOM()`
- [x] update examples
- [x] update tests
- [x] update documentation 

Cc @Olical 
Cc @djeeg from #90

### CODE REVIEW

**Comment by tibotiber** [comment]
@djeeg, some comments about the difference with your approach:
- I obviously did not go with Typescript.
- I didn't merge the `connectFauxDOM()` call into `withFauxDOM()`. This is to keep the same API users are already familiar with, and it also makes it possible to hold several faux nodes in a single component.
- I used an inheritance inversion so that we can directly manipulate the wrapped component's state, lifecycle methods, and class methods. This is probably the point to get animation sorted in your implementation.

Let me know what you think about these things :).

**Comment by tibotiber** [comment]
An additional note: the use-case here is actually very suitable for inheriting a component similarly to `PureComponent` but that would require users to know about the implementation so they don't override the lifecycle methods we use in their component without using `super`. That's the advantage of using an HOC with inverted inheritance, we can implement the careful inheritance and the user doesn't have to care.

**Comment by djeeg** [comment]
hey @tibotiber, I have done some testing of your inversion HOC withFauxDOM, lgtm.

**Comment by djeeg** [comment]
Whats your suggestion for rendering multiple instances of the same component?

This is what i have currently.

```
class NameOfReport extends React.Component<IProps, any> {
    constructor (props) {
        super(props)
        var elementid = "chart_NameOfReport_" + shortid();
        this.state = { elementid : elementid, [elementid]: "loading..." }
    }
    componentDidMount() {
        var faux = (this as any).connectFauxDOM('div', this.state.elementid);
		//...
    }
    render() {
        var elementid = this.state.elementid;
        var result = (
            <div>
                <div className={elementid}>
                    {this.state[elementid]}
                </div>
            </div>
        );
        return result;
    }
}
export default withFauxDom(NameOfReport);
```

**Comment by tibotiber** [comment]
@djeeg I'm guessing you meant to ask how to render multiple charts in a single component, did you? If that is the case you would call `connectFauxDOM()` twice in `componentDidMount()` and render each node separately in `render()`.
```js
// ...
componentDidMount() {
  // ...
  var fauxNode1 = connectFauxDOM('div', 'chart1');
  var fauxNode2 = connectFauxDOM('div', 'chart2');
}

render() {
  // ...
  {this.state.chart1}
  // ...
  {this.state.chart2}
}
```
Please note that I have never used this behaviour myself and am not advocating it. In many cases, I think rendering different components may be a better idea. But since it was a possibility of the API, I'd rather not remove it. I also think it is easier to reason about the HOC when you don't pass usage arguments to it, it basically injects class methods that you can use but does not originally change the state for you which keeps it pure.

**Comment by tibotiber** [comment]
@Olical any idea on how to handle testing for this?

**Comment by Olical** [comment]
Hm, I'll have a look. I've never been too good at testing more complex UI things, anything more than pure views tend to perplex me :smile:

**Comment by tibotiber** [comment]
I rebased and updated to match the API of #89. Will look into HOC testing as well when I have some time, haven't done that before.

**Comment by tibotiber** [comment]
@Olical I fixed the tests for the HOC. There is a failing test that has nothing to do with this PR though, I tried it on master and it is failing there as well.

**Comment by tibotiber** [comment]
I updated the docs and other links, the PR is ready :)

**Comment by tibotiber** [comment]
Added some links to the README, see #92 (did it here to avoid conflicts due to README updates in this PR)

**Comment by Olical** [comment]
(I haven't forgotten and will sort out the old mergeroo soon, I've just had a couple of very busy works + studying a new coursera course in my free time :smile:)

**Comment by tibotiber** [comment]
Thanks for the heads up Oliver. Any ETA on the merge? 
Also any idea on the failing test? It doesn't seem to come from these changes, were you aware of it previously?

**Comment by Olical** [comment]
If I had to guess, it's some new property D3 tries to use, it may just need to be implemented. I'll take a look this week :smiley:

**Comment by Olical** [comment]
If you would like to merge master in the tests will start to pass again. Also, I was dumb and added a link to your article in a commit, which now conflicts with yours. But I prefer your separate articles section, so feel free to take that during the merge conflict resolution! It should be really easy. Once you're up to date with master and you've replaced my addition of your post link, I'll be happy to merge.

For some reason D3 started using a new method to access some style properties, I wasn't sure on the difference, so I just pointed this new method at the existing style property getter.

**Comment by tibotiber** [comment]
I rebased and fixed the conflicts. There is a failing test but apparently unrelated to the HOC. Looking into it. Any idea @Olical?

**Comment by Olical** [comment]
Oh, that's very odd. I'll take a look.

**Comment by tibotiber** [comment]
:tada:

**Comment by Olical** [comment]
Thanks for the work, you rock :D

**Pull request merged**
