### PR TITLE
Return correct querySelector/All value for falsies

### PR DESCRIPTION
**Pull request by pemrouz**

### CODE REVIEW

**Comment by Olical** [comment]
Looks good to me :) would you be able to add a short test that checks for the empty array response? I think I already have tests around this so it shouldn't be hard to add an extra one.

Thanks!

**Comment by Olical** [comment]
The PR thinks there's a conflict for some reason, so I'm merging it manually and writing some tests. Thanks :)

**Comment by Olical** [comment]
Writing tests for this, it isn't required. The query selector implementation I use already returns an empty array if it doesn't match anything. Is this some edge case you found? Can you try out my master branch and let me know if it's okay? I made it so the `querySelector` function returns null when nothing is found though.

**Comment by pemrouz** [comment]
IIRC, this was for when `selector === undefined || null`. Might be better to fix this upstream?

**Comment by Olical** [comment]
Yep, realised that after the fact, I've tried it out in the browser and
replicated that functionality with tests now.

When nothing is found for querySelectorAll, it returns an empty array, as
you'd expect. If you do not pass a selector it throws an error, as per the
browser spec.

So if the selector is null or undefined it should throw. I thought that was
kind of weird, but still.

Also made querySelector return null if it doesn't match anything, not
undefined.

**Pull request closed without merging**
